### ISSUE TITLE
Failing to start process

### ISSUE THREAD

**Issue by andrewparmet** [wix/wix-embedded-mysql#102]
I'm able to build and run locally, but when I try to build on a Jenkins server I get the following error:

```
17:16:49.088     2017-06-14 17:16:49,086 INFO  [Test worker] - Preparing EmbeddedMysql version 'Version 5.6.35'...
17:16:49.206     2017-06-14 17:16:49,204 INFO  [Test worker] - Preparing mysqld for startup
17:16:49.321     Master tearDown
17:16:49.348 Gradle Test Executor 1 finished executing tests.
17:16:49.351 
17:16:49.352 com.mypackage.CompleteTestSuite > classMethod FAILED
17:16:49.352     java.lang.RuntimeException: Command exited with error code: '1' and output: ''
17:16:49.352         at com.wix.mysql.distribution.setup.ProcessRunner.resolveException(ProcessRunner.java:50)
17:16:49.352         at com.wix.mysql.distribution.setup.ProcessRunner.run(ProcessRunner.java:35)
17:16:49.352         at com.wix.mysql.distribution.setup.NixBefore57Initializer.apply(NixBefore57Initializer.java:33)
17:16:49.352         at com.wix.mysql.distribution.Setup.apply(Setup.java:26)
17:16:49.352         at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:42)
17:16:49.352         at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:21)
17:16:49.353         at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
17:16:49.353         at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:47)
17:16:49.353         at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:155)
```

Has anyone ever seen this before, or can you recommend any way of trying to debug this?
Thanks!

Update: If I change the version of MySQL I want to run to 5.7, this error does not occur.

**Comment by viliusl** [comment]
Hi @andrewparmet, cannot recall. It's unfortunate there is no proper feedback in this case, but mysql sometimes has an opinion of it's on in reporting errors and I'm unaware of special requirements that `5.6` would have over `5.7`. Init scripts are different - `5.7` comes with initialization via `mysqld` executable whereas `5.6` uses [mysql_install_db](https://dev.mysql.com/doc/refman/5.6/en/mysql-install-db.html) perl script, so there might be that.

Is `5.7` ok for you?

**Comment by andrewparmet** [comment]
In general I prefer 5.7 but my use case involves Amazon Aurora which is pinned to 5.6 compatibility. All it means is I have to be a little more careful not to rely on the newest features.

I didn't realize that 5.6 uses a Perl script - my guess is that's causing an issue somewhere. I don't know if Perl is installed in the environment where this is running.

**Comment by andrewparmet** [comment]
Punting.

**Comment by er1c** [comment]
I had this same error occur using the Windows 10 Linux Subsystem, and running If I changed to `5.7`:

```
[error] Caused by: sbt.ForkMain$ForkError: java.lang.RuntimeException: Command exited with error code: '127' and output: ''
[error]         at com.wix.mysql.distribution.setup.ProcessRunner.resolveException(ProcessRunner.java:50)
[error]         at com.wix.mysql.distribution.setup.ProcessRunner.run(ProcessRunner.java:35)
[error]         at com.wix.mysql.distribution.setup.Mysql57Initializer.apply(Mysql57Initializer.java:35)
[error]         at com.wix.mysql.distribution.Setup.apply(Setup.java:26)
[error]         at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:42)
[error]         at com.wix.mysql.MysqldExecutable.start(MysqldExecutable.java:21)
[error]         at de.flapdoodle.embed.process.runtime.Executable.start(Executable.java:101)
[error]         at com.wix.mysql.EmbeddedMysql.<init>(EmbeddedMysql.java:47)
[error]         at com.wix.mysql.EmbeddedMysql$Builder.start(EmbeddedMysql.java:155)
[error]         at ta.db.TestDB$.<init>(TestDB.scala:43)
```

As I understand there isn't (this still isn't), but adding the comment in case someone else encounters and also comes up with what the underlying problem is.

**Comment by BorzdeG** [comment]
broke in v5_7_18 - v5_7_17 works correctly. At the same time, Windows 10 Linux Subsystem was removed and installed - there was no difference
