### ISSUE TITLE
Add the possibility to add parameters when execute mysql_install_db

### ISSUE THREAD

**Issue by VitoMezzapesa96** [wix/wix-embedded-mysql#134]
I have the following error when start EmbeddedMysql: 
> Please configure the 'hostname' command to return a correct hostname.

In order to skip the resolve of ip made by sql I need to insert **--force** when execute scripts/mysql_install_db. 
I suggest to add an object (Like IRuntimeConfig) that gives the mysql_install_db parameters.

**Comment by viliusl** [comment]
@VitoMezzapesa96 maybe `--force` should just be on by default? from mysql docs:
```
Cause mysql_install_db to run even if DNS does not work. Grant table entries normally created using host names will use IP addresses instead. 
```

It seems that it will be ok for type of our use-case: short-lived mysql instance. wdyt?

**Comment by VitoMezzapesa96** [comment]
@viliusl Thinking on this way I totally agree with you!

**Comment by viliusl** [comment]
@VitoMezzapesa96 - version `4.0.1` released with `--force` enabled by default. Now closing issue - reopen or let me know if there will be any other issues.
