### ISSUE TITLE
Documentation Request : How can I select some rows by query and assert query output using Java?

### ISSUE THREAD

**Issue by ahmedmohiduet** [wix/wix-embedded-mysql#136]
How can I select some rows by query and assert query output? I have some examples in Scala but too looking for java examples

**Comment by viliusl** [comment]
@ahmedmohiduet - whole select/query/work with mysql is really out of scope of this library. There are limitless resources on internets and I don't feel there is a need to add more of it.

tests do contain most basic `JdbcTemplate` usage - https://github.com/wix/wix-embedded-mysql/blob/master/wix-embedded-mysql/src/test/scala/com/wix/mysql/support/IntegrationTest.scala#L108 and scala is of no essence there - really close to java code.
