### ISSUE TITLE
failed with message 'Broken pipe'

### ISSUE THREAD

**Issue by javydreamercsw** [wix/wix-embedded-mysql#140]
I'm loading three scripts for some testing [here](https://github.com/javydreamercsw/Countries-States-Cities-database/tree/javydreamercsw-fix-issue-32) but is failing with a broken pipeline on the last one, which is quite large.

**Comment by viliusl** [comment]
@javydreamercsw - ok, so `wix-embedded-mysql` provides basic support for loading scripts for simple cases. For advanced ones I would recommend just to use https://flywaydb.org/, https://www.liquibase.org/ or similar - they are much more robust in this regards.
