### ISSUE TITLE
Unable to run maven test with embeded My SQL getting Missing dependency Exception.

### ISSUE THREAD

**Issue by ZeeshanDamani** [wix/wix-embedded-mysql#158]
I am using embedded Mysql in my Maven test but When I am running my test I am getting 
`com.wix.mysql.exceptions.MissingDependencyException: System library 'libaio.so.1' missing` Exception.

Maven dependency : 
`
        <dependency>
            <groupId>com.wix</groupId>
            <artifactId>wix-embedded-mysql</artifactId>
            <version>4.0.1</version>
            <scope>test</scope>
        </dependency>
`

Os ubuntu 16.04 LTS

**Comment by viliusl** [comment]
I know this is annoying, but https://github.com/wix/wix-embedded-mysql#known-issues - and there is not much I can do about it as it's really platform-specific. I do support windows/linux/mac - supporting different variants of linux is just too much.
