### ISSUE TITLE
Changing extraction destination

### ISSUE THREAD

**Issue by ericneu** [wix/wix-embedded-mysql#165]
I don't think this is a unique situation, but, I have my source code and build directories on a partition that is backed up by our corporate infrastructure, however, due to security policies binaries and scripts can not be executed from that partition.  When trying to use this project for junit testing database interfaces it extracts to the project's target folder which is a folder on a noexec partition, I need to have it extract to another folder which is on a partition that has exec privileges.  Is there already an option that I can't find that addresses this?

**Comment by chapmbk** [comment]
Can't you set it when you are building the config?
final MysqldConfig config = aMysqldConfig(version)
    .withPort(port)
    .withTempDir("directory goes here")

**Comment by ericneu** [comment]
Isn't that just what mysql uses as a temp directory?  If it is the actual install directory that would be fine.  Our admins informed me that the partition I was using could in fact be mounted with execute permission (recent policy change) so I'm actually good.

**Comment by viliusl** [comment]
all good, closing:)
