### ISSUE TITLE
add support for MySql 8.0.x

### ISSUE THREAD

**Issue by shai125** [wix/wix-embedded-mysql#170]
Hi,
It would be great if you could support the latests version of MySql 8.0.x.

MySQL 8.0 has the feature of common table expressions, and it will be great if we could use `wix-embedded-mysql` to test these queries.

**Comment by ngueno** [comment]
There is a [PR](https://github.com/wix/wix-embedded-mysql/pull/147) open already for this, but without updates.
I am also waiting for the feature :) it would be great to have it on master.

**Comment by viliusl** [comment]
@shai125 @ngueno - I know - tried that but then got to windows and progress stalled:/ Will try to push it.

**Comment by viliusl** [comment]
Released in version 4.5.0
