### ISSUE TITLE
Documentation of wix-embedded-mysql-download-and-extract is incorrect

### ISSUE THREAD

**Issue by twang-apixio** [wix/wix-embedded-mysql#171]
The documentation has the following useage:

```java -jar wix-embedded-mysql-download-and-extract-2.2.7-SNAPSHOT-jar-with-dependencies.jar $majorVersion $minorVersion```

This is incorrect. The command line requires parameter 0 to be the cache directory but will throw with a cryptic error, using the majorVersion as the cache directory, minor version as latest and the user will have to read the code to figure out what happened.

**Comment by viliusl** [comment]
fixed by https://github.com/wix/wix-embedded-mysql/pull/169
