### ISSUE TITLE
improve docs

### ISSUE THREAD

**Issue by viliusl** [wix/wix-embedded-mysql#27]
Update readme.md to make examples clearer - now they look nice, but magic with static imports makes it  hard to reproduce it in code - copy/paste.

**Comment by ittaiz** [comment]
I have a vague recollection that someone solved this already (maybe have a code button or something). Just food for thought.



—

**Comment by viliusl** [comment]
Thanks, I so much miss possibility to have multi-language code examples:/ Otherwise it's just a tip for myself that code example are not really helpful.

and .md is really limited. It's either I have nice snippets + links to tests showing actual usage, or proper examples.

or... github.io, but meh, not yet:)

**Comment by noam-almog** [comment]
docs looks great just add the static import statement.

**Comment by viliusl** [comment]
And then they will stop looking great:)

On Fri, Sep 4, 2015 at 4:31 PM, Noam Almog <notifications@github.com> wrote:

> docs looks great just add the static import statement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wix/wix-embedded-mysql/issues/27#issuecomment-137738735>
> .
>



-- 

*Vilius Lukošius*

Software Engineer


Cell: +37061111226

33 Didžioji St./ 2 Rudininku St. Vilnius Lithuania

**Comment by noam-almog** [comment]
they will look a little less good but they will compile... and compiling
code sample is the bare minimum 😉

On Friday, September 4, 2015, Vilius Lukošius <notifications@github.com>
wrote:

> And then they will stop looking great:)
>
> On Fri, Sep 4, 2015 at 4:31 PM, Noam Almog <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > docs looks great just add the static import statement.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/wix/wix-embedded-mysql/issues/27#issuecomment-137738735
> >
> > .
> >
>
>
>
> --
>
> *Vilius Lukošius*
>
> Software Engineer
>
>
> Cell: +37061111226
>
> 33 Didžioji St./ 2 Rudininku St. Vilnius Lithuania
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wix/wix-embedded-mysql/issues/27#issuecomment-137740829>
> .
>


-- 


“We cannot solve our problems with the same thinking we used when we
created them.”

~Albert Einstein

**Comment by viliusl** [comment]
no complaints, works for now
