### ISSUE TITLE
upgrade flapdoodle process to 1.50.0

### ISSUE THREAD

**Issue by noam-almog** [wix/wix-embedded-mysql#28]
The migration is easy and tests are passing, but I get alot of warnings in the logs.
lets discuss this.

**Comment by viliusl** [comment]
Not sure what warnings you are talking about, but migration without any functional changes yielded me same results.

I also migrated to ExtractedArtifactStore which was a little harder, but then again it gives us caching out of the box, so worth it. see https://github.com/wix/wix-embedded-mysql/commit/c7213d074b4ffdce12dd9a195a622ebf5fe34a7a

Now just have to extract that pesky PackagePaths to property files and bind them to versions:)

**Comment by noam-almog** [comment]
@viliusl it keeps complaining it cannot shut down the process, false positive, but still, we need to fix that as well.

**Comment by viliusl** [comment]
@noam-almog - do you see those errors in your project or wix-embedded-mysql builds? sample project please, because I'm not seeing that anywhere right now.
