### ISSUE TITLE
server timezone should be UTC by default

### ISSUE THREAD

**Issue by ronnyelkayam** [wix/wix-embedded-mysql#32]
In my project the database generates timestamps on update (as trigger)
The database should be configured to have default timezone UTC (or at least an option to change that)
This is what I am doing in the meantime:
    val rootDs = PhotographyDbConfig(DefaultDBHost, DefaultPort, "root", "", PhotographyDbName).toRootDataSource
    val db= new JdbcTemplate(rootDs)
    println(s"Patch to fix timezone - start ${db.queryForMap("""SELECT @@session.time_zone;""").values.toString} ${db.queryForMap("""SELECT @@global.time_zone;""").values.toString}...")
    println(s"Patch to fix timezone - execute ${db.execute("""SET @@session.time_zone = "+00:00";""")}")
    println(s"Patch to fix timezone - execute ${db.execute("""SET @@global.time_zone = "+00:00";""")}")
    println(s"Patch to fix timezone - end ${db.queryForMap("""SELECT @@session.time_zone;""").values.toString} ${db.queryForMap("""SELECT @@global.time_zone;""").values.toString}")

**Comment by viliusl** [comment]
Ok, will do, but will add support only for offset-based timezones.

What this means is that by querying database you won't be able to get named timezone (UTC), but will get offset like you do (+00:00).

To have proper named-timezone support I would have to do additional steps like populating tz system tables from tzInfo, but then it's additional step in bootstrap process (extra duration) and would not work on windows....

**Comment by noam-almog** [comment]
@viliusl lets just set everyone to UTC by default, no need to expose this as a parameter.

**Comment by ronnyelkayam** [comment]
If you are setting everyone to utc, then there is a simpler way to do that:
you can change the timezone in the config file that comes with the database
or add a parameter to mysqld with the timezine

**Comment by viliusl** [comment]
@noam-almog too late:) Also my idea is to provide defaults and enable to fine-tune to your production environment as an option (just like charset). So really easy to add to MysqldConfig builder. Consistency.

**Comment by noam-almog** [comment]
@viliusl looks fine to me, the default right now is UTC which is exactly what I wanted.

**Comment by ronnyelkayam** [comment]
Amazing turnaround! Thanks
