### ISSUE TITLE
charsets are being ignored

### ISSUE THREAD

**Issue by noam-almog** [wix/wix-embedded-mysql#33]
No matter what I use it's still UTF8 or something like that.
This is an urgent bug, we need to resolve it as fast as possible

CC: @tempit

**Comment by viliusl** [comment]
Hej,

If you want some help from my side, i'll need more info:
- server encoding?
- schema encoding?
- jdbc conn string?

Or just a failing test:)

**Comment by tempit** [comment]
Check out the ITs in github.com/wix/Calculon
They used to pass, now they fail.

**Comment by viliusl** [comment]
Ok, will do that.

**Comment by viliusl** [comment]
There is no bug there, just a non-intuitive behavior:/

**Comment by noam-almog** [comment]
@viliusl All what I see is that mysql limits the size of the index, the limit shows that no matter which encoding I use for the DB i get the same limitation so it seems like the parameter doesn't work. Eyal showed me the wix config that has the charset param, perhaps we need to be able to inject those values into our config allowing us to be closer to production.

**Comment by viliusl** [comment]
No. Limitation is dependent on database encoding - had same issue, whereas
moving from utf8mb4 to latin1 solved the issue.

There are techinques to increase index-limit for innodb though, but then
again it's #notthateasy:)

On Tue, Oct 13, 2015 at 2:10 PM, Noam Almog <notifications@github.com>
wrote:

> @viliusl <https://github.com/viliusl> All what I see is that mysql limits
> the size of the index, the limit shows that no matter which encoding I use
> for the DB i get the same limitation so it seems like the parameter doesn't
> work. Eyal showed me the wix config that has the charset param, perhaps we
> need to be able to inject those values into our config allowing us to be
> closer to production.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wix/wix-embedded-mysql/issues/33#issuecomment-147684858>
> .
>



-- 

*Vilius Lukošius*

Software Engineer


Cell: +37061111226

33 Didžioji St./ 2 Rudininku St. Vilnius Lithuania

**Comment by noam-almog** [comment]
how can we make the schema inherit the charset ? connection url ?

**Comment by viliusl** [comment]
What I mean is that we have 2 encodings:
 - instance (mysqld) encoding;
 - schema (database) encoding;

Now schema (database) encoding defaults to utf8mb4 regardless of instance
encoding which is counterintuitive. I would say that SchemaConfig should
default not None if you do not set it explicitly via SchemaConfig.Builder
and then use whatever is set on instance.

On Tue, Oct 13, 2015 at 2:25 PM, Noam Almog <notifications@github.com>
wrote:

> how can we make the schema inherit the charset ? connection url ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wix/wix-embedded-mysql/issues/33#issuecomment-147688737>
> .
>



-- 

*Vilius Lukošius*

Software Engineer


Cell: +37061111226

33 Didžioji St./ 2 Rudininku St. Vilnius Lithuania
