### ISSUE TITLE
can't load .sql files from unexploded jars in classPathFiles

### ISSUE THREAD

**Issue by grunzwei** [wix/wix-embedded-mysql#36]
i'm using the embedded-mysql
there is a function
classPathFile
basically it does new File(resource.toURI)
this doesn't work for me when running maven, because everything is in a jar, so there is no file in the file that it can access
my jar depends on test-utils jar in test scope, and it has the mysql init code in main
this can be solved using java 8 filesystem

**Comment by noam-almog** [comment]
do you have your files packed in the classes resources or test resources ?
basically we load files from the classpath so if the are on other jars it's still possible to read them.

**Comment by grunzwei** [comment]
you load them by doing something equivalent to new File(resource.URI)
if the uri is internal to a jar, this doesn't work.
you can work around this using new java8 filesystem abstraction.
my files are packed in main/resources of a jar that i depend on in test scope, so it comes as an unexploded jar.

**Comment by viliusl** [comment]
@grunzwei - ok, so I might just have to `loadResourceAsStream()` instead. Will have to add test to verify it. What I don't want to do yet is to make this library bound to java 8 - there is no real reason for that, so why not leave door open for poor java 7 users:)

**Comment by noam-almog** [comment]
@viliusl had we used guava we wouldn't have this issue, no ? ;)

**Comment by viliusl** [comment]
Haven't check. Problem with guava I had was that I could not use most
recent version due to conflicts with framework, but maybe even not most
recent would cut it.

I will play with it once I will have time. Hopefully next week.

On Wed, Jan 6, 2016 at 10:46 AM, Noam Almog <notifications@github.com>
wrote:

> @viliusl <https://github.com/viliusl> had we used guava we wouldn't have
> this issue, no ? ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wix/wix-embedded-mysql/issues/36#issuecomment-169268513>
> .
>



-- 

*Vilius Lukošius*

Software Engineer


Cell: +37061111226

33 Didžioji St./ 2 Rūdninkų St., Vilnius, Lithuania

**Comment by hugebdu** [comment]
@viliusl any progress on that?
I'm trying to migrate projects to wix-embedded-mysql and looks like it is an issue.

**Comment by dkomanov** [comment]
@hugebdu https://github.com/wix/wix-embedded-mysql/commit/48a0ebc93799eaf48af81bc808f54ba67ea5a044

**Comment by dkomanov** [comment]
@hugebdu and the little script:
```
  def loadResources(path: String): Seq[String] = {
    if (path.isEmpty) {
      Nil
    } else {
      val resources = new PathMatchingResourcePatternResolver().getResources(path)
      resources.sortBy(_.getFilename).map(r => IOUtils.toString(r.getInputStream, java.nio.charset.Charset.forName("UTF-8")))
    }
  }
```

Use like `reloadSchema(aSchemaConfig... withCommand(loadResources("classpath:*.sql")))`

**Comment by hugebdu** [comment]
@dkomanov [your commit](https://github.com/wix/wix-embedded-mysql/commit/48a0ebc93799eaf48af81bc808f54ba67ea5a044) is not yet merged, right?

**Comment by dkomanov** [comment]
My PR merged: https://github.com/wix/wix-embedded-mysql/pull/43

**Comment by viliusl** [comment]
@hugebdu - I did an impl for this (https://github.com/wix/wix-embedded-mysql/commits/scripts-in-jar), but still thinking on naming and apis - which should be deprecated/supported. So @dkomanov solution will work for you right now.
