### ISSUE TITLE
Support proxy

### ISSUE THREAD

**Issue by tleveque** [wix/wix-embedded-mysql#54]
Embedded Mongo supports proxy definition.
It would be nice to have the same feature for embedded-mysql.

**Comment by viliusl** [comment]
Ok, on it - given I'm taking a slight departure from flapdoodle api, I will need to think a bit how to add it, but I have a working impl already, so I expect to ship it during next week if all is well.

**Comment by viliusl** [comment]
@tleveque - sorry for taking much longer than I anticipated - work, life...

Anyway - is it still needed? I did some experimenting with introduction of this but did not like how it turned out. If it's still needed I will continue and will finish it eventually.

**Comment by keihiromasa** [comment]
Hi.

I really appreciate if embeddedmysql supports proxy, since I wanna use embeddedmysql at my office but can't download tar.gz because of the proxy.

I download tar manually and put it to .embeddedmysql folder, but it still try to download tar.

**Comment by viliusl** [comment]
@keihiromasa ok, first need to stabilize ci - for some reason started just failing..., Then add proxy support. I would expect eta < 1 month - work, life, summer:)

**Comment by kazuki43zoo** [comment]
I will expect to support a proxy server with authentication. (I use it in my office)
Thanks.

**Comment by mikesmithson** [comment]
Is this still being worked on? Proxy support would be nice since I work behind a corporate firewall. If not, I can work on something and submit a PR.

**Comment by viliusl** [comment]
@mikesmithson PR is in progress - I don't like API yet though. Can you take a look @ it - now I will support basic proxy with no auth: https://github.com/wix/wix-embedded-mysql/pull/120

**Comment by viliusl** [comment]
@tleveque @mikesmithson @kazuki43zoo @keihiromasa - basic http proxy support released in 3.1.0 version, would love if you could check if that works for you - and if not we can build on it to add support for auth and other possible versions. Docs - https://github.com/wix/wix-embedded-mysql#customizing-download-settings

**Comment by mikesmithson** [comment]
will look at it today, thanks.

**Comment by viliusl** [comment]
@mikesmithson any luck?

**Comment by viliusl** [comment]
initial support added, closing.
