### ISSUE TITLE
not safe to start multiple instances of embedded mysql for same major version

### ISSUE THREAD

**Issue by viliusl** [wix/wix-embedded-mysql#55]
Now they share several resources:
 - temp fodler is fixed to `./target/mysql-5.x`;
 - running multiple downloads in parralel is not safe.
 - might be some temp file issues (sock ir such).

Given you run multiple instances in parallel, it pretends to work (and starts), but it is in an inconsistent state as they potentially share database files and shutdown for only one instance will succeed.

Solution:
 - either think of a way to enable multiple parallel runs;
 - fail fast if another instance is being started in same process.

**Comment by viliusl** [comment]
@noam-almog given it's in a single process, then yes, but we might have a set-up, where multiple jvms are forked for a single module (I'm sure you can do that via maven as well), then I have to do some fs-locking and that is plain annoying:/ Also I still get issues with multiple downloads - let's say you have a clean state (mysql files are not cached in ~./embedmysql), then multiple processes/runs start downloading it/extracting it and I'm not even sure what will happen then:/

So it's doable, but not sure I wanna go there.

**Comment by noam-almog** [comment]
I don't know if you remember, but the initial implementation used random guid on target dir, so user could have created as much instances he wanted but we changed it to fix the FW issues on osx.
To sync stuff here, because you can have multiple builds running on multiple processes you must use a file lock, there is no way around this.

**Comment by viliusl** [comment]
@noam-almog - you are correct, but after cleaning-up all startup/preparation scripts now it's clear how multiple instances can be separated. I did a PR, ci for linux, osx, windows seem to pass, so I will merge this PR on Monday if all is good.
