### ISSUE TITLE
support config of  target path

### ISSUE THREAD

**Issue by redmark** [wix/wix-embedded-mysql#65]
The embeded mysql start from  ./target  directory,   it is ok for  maven.  If  gradle is used,   ./build  is preferred.

**Comment by viliusl** [comment]
Ok,

Is it a show-stopper for you or just an annoyance?

I will implement it, but if it's not a show-stopper I will not push it too hard, as I need to do some thinking on overall config arrangement as there are some other things in the pipeline (network config - proxy). Given these are API changes I don't want to regret them later.

**Comment by rmannibucau** [comment]
+1 for this feature, using maven this kind of thing often go in target (the temp data folder). Would also be nice to be able to split the executable (we'd likely put in a repo or cached location) and the test data folder.

This is the only blocking thing for me to migrate from the old mysql-mxj

**Comment by viliusl** [comment]
fixed via #96, version 2.1.9 released, please let me know if have any further issues.
