### ISSUE TITLE
Mysql server configuration

### ISSUE THREAD

**Issue by xnull** [wix/wix-embedded-mysql#77]
Hey hello,
I have an issue with Case Sensitivity in table names.
I have upper case table names in my database and lower case table names in my code. I have to make it [case insensitive](http://dev.mysql.com/doc/refman/5.7/en/identifier-case-sensitivity.html). I see 2 ways to setup it:

1. Customize my.cnf file to change default settings.
2. update information_schema with SQL request.

I don't know if it's possible to change my.cnf in your library and the idea with update script doesn't work too:
`
EmbeddedMysql mysqld = anEmbeddedMysql(config)
                    .addSchema("my_schema",
                            Sources.fromFile(new File("database/mysql/initial.sql")),
                            Sources.fromString("update information_schema.GLOBAL_VARIABLES set VARIABLE_VALUE=2 where VARIABLE_NAME='LOWER_CASE_TABLE_NAMES';")
                    )
                    .start();
`

I get an error:
> com.wix.mysql.exceptions.CommandFailedException: Command 'update information_schema.GLOBAL_VARIABLES set VARIABLE_VALUE=2 where VARIABLE_NAME='LOWER_CASE_TABLE_NAMES';' on schema 'my_schema' failed with errCode '1' and output 'ERROR 1044 (42000) at line 1: Access denied for user 'root'@'127.0.0.1' to database 'information_schema'

Maybe you can help me with it or you have some thoughts how to do it?
Anyway, at least, it would be nice to have an ability to setup my.cnf in your library.

**Comment by viliusl** [comment]
Hej,

Ok, so I looked into it and I don't yet want to enable `information_schema` modification as this is not smth you usually do when applying your db migrations.

Given that my current idea is to allow you to provide arbitrary [server options](http://dev.mysql.com/doc/refman/5.7/en/server-options.html) via MysqldConfig builder like:

```
MysqldConfig config = aMysqldConfig(v5_6_23)
    .withPort(2215)
    .withSystemOptions("--lower_case_table_names=2")
    .build();
```

Now I will need to think about it a bit to think of some cases like when you try to override system option that is managed by a library - precedence, resolution rules, etc.

In short - on it.

**Comment by xnull** [comment]
Hi, Vilius,
That's great, thank you. I look forward to getting  improvements from you.

**Comment by viliusl** [comment]
Hej, 2.1.1 version released with support for arbitrary server options:

```java
MysqldConfig config = aMysqldConfig(v5_6_23)
    .withServerVariable("max_connect_errors", 666)
    .build();
```

It should be available from maven central later today. Enjoy!

/V

**Comment by xnull** [comment]
Thanks a lot
