### ISSUE TITLE
Upgrade MySQL to 5.7.16 and 5.7.17. Add support for 5.7.17 and Mac OSX Sierra.

### ISSUE THREAD

**Issue by rafal-glowinski** [wix/wix-embedded-mysql#80]
There have been two new versions of MySQL released: 5.7.16 for Mac OSX 10.11 (El Captain) and 5.7.17 for Mac OSX 10.12 (Sierra). They should be included.

**Comment by rafal-glowinski** [comment]
Ok there are two problems:
1) It seems that Oracle / MySQL moved their files to HTTPS so default configuration needs to be changed.
2) Version 5.7.17 has a different OS name in path: https://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.17-macos10.12-x86_64.tar.gz (it used to be 'osx' and now it is 'macos'). To compare with 5.7.15: https://downloads.mysql.com/archives/get/file/mysql-5.7.16-osx10.11-x86_64.tar.gz

**Comment by viliusl** [comment]
v2.1.2 with https fix released, should be available shortly via central.

**Comment by rafal-glowinski** [comment]
Thanks!

**Comment by viliusl** [comment]
Hej, your PR merged and released. v2.1.3 should be available in maven central shortly.
