### ISSUE TITLE
Download of MySQL Fails

### ISSUE THREAD

**Issue by michaelruocco** [wix/wix-embedded-mysql#82]
I have had this issue raised against the gradle plugin project I have written that wraps this library: https://github.com/michaelruocco/embedded-mysql-plugin/issues/2. The issue looks to be quite simple on the face of it, the download of MySQL is failing, and I think this is due to the download page on the MySQL website being moved from https://dev.mysql.com/get/Downloads/ to https://www.mysql.com/downloads/.

I can create a pull request to have a go at fixing this but I wanted to raise it first to get your view incase I am missing something or have not found the root cause of the issue.

**Comment by noam-almog** [comment]
@michaelruocco Thanks, we've already noticed it yesterday and fixed it. I checked in a change in the snapshot version. I'll release a newer version soon.

**Comment by michaelruocco** [comment]
@noam-almog ah okay perfect, thanks for the quick response!

**Comment by viliusl** [comment]
Hi @michaelruocco - v 2.1.2 with https fix released, should be available shortly via central.

And thanks for letting us know about the issue!

**Comment by michaelruocco** [comment]
@viliusl Thanks for letting me know. Sorry, I probably should have checked in more detail to see that it was in hand before raising the issue. My local tests seem to have resolved the issue as far as I can see.
