### ISSUE TITLE
Failing on macOS Sierra should give a more helpful message

### ISSUE THREAD

**Issue by hmemcpy** [wix/wix-embedded-mysql#85]
Took me a while to figure out why `Platform OS_X is not in a supported platform list: OS_X,Windows,Linux`.

The message should hint at the minimal supported version on Sierra.

**Comment by viliusl** [comment]
Thanks @hmemcpy  for issue - you are right - for one I need to list supported versions + also extend supported version list as now version marked say for 10.12 are also compatible with 10.11 and 10.10.

Wanna pull?

**Comment by hmemcpy** [comment]
Sure, I'd be happy to send a PR!
