### ISSUE TITLE
All MySQL download URLs are failing

### ISSUE THREAD

**Issue by raulgd** [wix/wix-embedded-mysql#87]
Hi,

When trying to set it up for the first time, I checked the downloaded gzip, changed the extension to HTML and it shows a Permanently Moved error with a link.

I think the download URLs need to be updated or else it will fail, or give instructions to manually setup if needed.

My machine is a MacOS Sierra, and selected both 5.6 and 5.7 for the test setup.

Thanks

**Comment by raulgd** [comment]
hey guys... I want to do a PR for updating the configuration.

Can I please get contributor permissions?

Thanks!

**Comment by noam-almog** [comment]
@raulgd which version are you using ? we fixed this (https redirect) in the last version

**Comment by raulgd** [comment]
2.1.1 which seems to be the latest.

Using this on my gradle script testCompile "com.wix:wix-embedded-mysql:2.1.1"

**Comment by raulgd** [comment]
The fix is a one-liner for class DownloadConfigBuilder.java, did this on line 14

```java
downloadPath().setDefault(new DownloadPath("https://cdn.mysql.com/archives/"));
```

**Comment by noam-almog** [comment]
[2.1.4](https://mvnrepository.com/artifact/com.wix/wix-embedded-mysql/2.1.4) is the latest 
https was fixed 2.1.2, please upgrade and let us know if you still encounter any issues ?

**Comment by raulgd** [comment]
Oh, sorry, 2.1.2 was what appeared to me from maven central, perhaps my index wasn't updated correctly, let me try it out right now

**Comment by raulgd** [comment]
Yeah, version 2.1.4 worked! wow thanks!

**Comment by raulgd** [comment]
Closing issue :)
