### ISSUE TITLE
Ability To Customize Download Path

### ISSUE THREAD

**Issue by PainHex** [wix/wix-embedded-mysql#93]
We want to use this on a project but currently struggling because of proxy issues. Would it be possible to add the ability to customize the download path? 

We could then just let our artifactory download the archive and we could get it from there.

**Comment by noam-almog** [comment]
@PainHex it would be possible with some effort, the main problem is that we can only expose a base url at the moment, then it would be up to you to create the proper directory structure in artifactory.
another option would be to support proxy which is something that came up in previous requests.

**Comment by PainHex** [comment]
Just exposing the base url at the moment would be fine, so long as we can change the domain its trying to get it from, then we're golden (We're fine with constructing the directory structure ourselves on Artifactory).

**Comment by noam-almog** [comment]
@viliusl we can expose base url with target path so we can handle this issue with #65, WDYT ?

**Comment by PainHex** [comment]
Addressed in version 2.2.0 - Closing
