### ISSUE TITLE
MysqlClient fails to connect to embedded database when .my.cnf is present

### ISSUE THREAD

**Issue by jgerken** [wix/wix-embedded-mysql#98]
When the user executing the embedded database has a `.my.cnf` in which she configured her default database connection, the MysqlClient will use the values for `password` and `host` from this file. If the configured database and the embedded database use the same port the MysqlClient will connect to the wrong database. Otherwise, it will fail to connect.

MysqlClient must explicitly use the following option `--host=localhost --password=`. I'll submit a pull request for that change.

**Comment by viliusl** [comment]
@jgerken 2.2.3 version is in central. Thanks for PR!
